# Generated by Django 4.2.16 on 2024-09-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="sypnosis",
            new_name="plot",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="color_class",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="info_link",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="status",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="trailer",
        ),
    ]
