# Generated by Django 4.2.16 on 2024-09-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movies",
            options={
                "ordering": ["title", "status"],
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
    ]
