# Generated by Django 4.2.16 on 2024-09-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
