# Generated by Django 4.2.16 on 2024-09-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
    ]
