# Generated by Django 4.2.16 on 2024-09-11 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_rename_sypnosis_movies_plot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movies",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
    ]
