# Generated by Django 4.2.16 on 2024-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_remove_movie_poster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["title"],
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
