# Generated by Django 4.2.16 on 2024-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_actor_production_rating_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
