# Generated by Django 4.2.16 on 2024-09-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_alter_moviecomment_movie"),
        ("movie", "0004_movies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
