# Generated by Django 4.2.16 on 2024-09-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_production_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ("id",),
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
    ]
