# Generated by Django 4.2.16 on 2024-09-27 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movie", "0005_alter_movie_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("approved", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_comments",
                        to="movie.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie comment",
                "verbose_name_plural": "Movie comments",
                "db_table": "movie_comment",
                "ordering": ["-created_on", "author", "approved"],
            },
        ),
    ]
