# Generated by Django 4.2.16 on 2024-09-16 09:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "profile_image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "About section",
                "verbose_name_plural": "About sections",
                "db_table": "about",
            },
        ),
        migrations.CreateModel(
            name="CollaborateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Collaboration Request",
                "verbose_name_plural": "Collaboration Requests",
            },
        ),
    ]
