# Generated by Django 4.2.16 on 2024-09-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "About section",
                "verbose_name_plural": "About sections",
            },
        ),
        migrations.AlterModelOptions(
            name="collaboraterequest",
            options={
                "verbose_name": "Collaboration Request",
                "verbose_name_plural": "Collaboration Requests",
            },
        ),
        migrations.RenameField(
            model_name="about",
            old_name="movie",
            new_name="content",
        ),
    ]
