# Generated by Django 4.2.16 on 2024-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboraterequest",
            name="phone",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="collaboraterequest",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
