# Generated by Django 4.2.16 on 2024-09-10 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_options_movie_status_movie_updated_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MovieComments",
            new_name="MovieComment",
        ),
    ]
