# Generated by Django 4.2.16 on 2024-09-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movies"),
        ("comment", "0002_rename_moviecomments_moviecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviecomment",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="movie.movies",
            ),
        ),
    ]
